"rectype","issueid","project_owner","project_name","actor","time","text","action","title"
"issue_title","658","nilearn","nilearn","dohmatob","2015-07-14 08:44:19","# 
## ERROR: nilearn.tests.test_datasets.test_fetch_adhd

Traceback (most recent call last):
  File ""/usr/lib/python2.7/dist-packages/nose/case.py"", line 197, in runTest
    self.test(*self.arg)
  File ""/home/elvis/CODE/FORKED/nilearn/nilearn/tests/test_datasets.py"", line 438, in test_fetch_adhd
    n_subjects=12, verbose=0)
  File ""/home/elvis/CODE/FORKED/nilearn/nilearn/datasets.py"", line 1653, in fetch_adhd
    dtype=None)
  File ""/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py"", line 1721, in genfromtxt
    output = np.array(data, dtype=ddtype)
OverflowError: Python int too large to convert to C long

BTW,  this is the contents of the .csv generated by the test case (which looks weird to me):
""# Subject""
33390385728031749
8650549469148439
4378444284640131
16685754674586676
17757804278344090
26264712857545098
36119777311222173
12917479214967171
41878941916772270
90275917604688
43499428783930
17885601032707231
17380349668994869
7211859975363044
98818608752748
6091964436794103
17154520289969762
6515714499656048
6710018826350358
15567529874352769
","start issue","Python int too large to convert to C long"
"issue_closed","658","nilearn","nilearn","lesteve","2015-07-15 13:52:36","","closed issue","Python int too large to convert to C long"
"issue_comment","658","nilearn","nilearn","dohmatob","2015-07-14 14:22:05","Fixed.
","",""
"issue_comment","658","nilearn","nilearn","lesteve","2015-07-15 13:52:36","I pushed a tiny improvement of the fix in https://github.com/nilearn/nilearn/commit/ddef38a299ed0fedeee5f16f6cc08060dd998018.
","",""
