"rectype","issueid","project_owner","project_name","actor","time","text","action","title"
"issue_title","71","pycqa","astroid","pylint-bot","2015-01-07 01:50:20","Originally reported by: **Fran√ßois Mockers (BitBucket: [mockersf](http://bitbucket.org/mockersf), GitHub: @mockersf?)**

---

When I run pylint on :

```
#!python

from hashlib import sha1

sha1().block_size
```

I get the following error :

```
E:  3, 0: Instance of 'sha1' has no 'block_size' member (no-member)
```

---
- Bitbucket: https://bitbucket.org/logilab/astroid/issue/71
","start issue","hashlib : block_size property is not recognized"
"issue_closed","71","pycqa","astroid","pylint-bot","2015-12-09 05:52:52","","closed issue","hashlib : block_size property is not recognized"
