,rectype,issueid,project_owner,project_name,actor,time,text,action,title,provenance,paths,plus_1,urls,issues,userref,code,formatted_time
358,commit_messages,,aio-libs,aioredis,pyup-bot,2017-07-04 16:13:56,Update pytest from 3.1.2 to 3.1.3,70df7257d43deacea5a18ed19982ee7dfd0efb3c,,"api.github.com,git_clone",[u'(unknown)'],False,[],[],[],[],2017-07-04
1282,pull_request_commit,261.0,aio-libs,aioredis,pyup-bot,2017-07-04 16:13:56,Update pytest from 3.1.2 to 3.1.3,2f1b2045f3d109b4465eeb225f349e248c7ada9e,,api.github.com,,False,[],[],[],[],2017-07-04
1283,pull_request_commit,262.0,aio-libs,aioredis,pfreixes,2017-07-04 23:03:54,"Support for MaxClientsError for connection and pool #186

When a new connection tries to get connected to the redis server and it
has been configured with a maximum number of connections, the client
will get a `MaxClientsError` exception if this limit is reached out.

Also if a pool initialization with a `min_size` that can meet the
requirements - beucase of that limit u others issues - the pool creation
will return also a `MaxClientsError`.",fc2d573c9a2cd92dc2c44370bf12b7fd89fa5a61,,api.github.com,,False,[],"[{u'raw': u'#186', u'refstyle': u'#d', u'parts': [u'aio-libs', u'aioredis', u'186', u'']}]",[],[],2017-07-04
1323,pull_request_commit,295.0,aio-libs,aioredis,pyup-bot,2017-07-04 16:13:56,Update pytest from 3.1.2 to 3.1.3,70df7257d43deacea5a18ed19982ee7dfd0efb3c,,api.github.com,,False,[],[],[],[],2017-07-04
